set -g mouse on
set-option -g prefix C-a

bind C-a send-prefix
bind a last-window

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed

set -g set-titles on          # set terminal title

set -g history-limit 50000    # boost history

set -g default-terminal "tmux-256color"

# Tell tmux that the host terminal (Ghostty) supports true color (RGB)
set -as terminal-features ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-256color:Cc:Cr:RGB"

# Enable undercurl and styled underlines support inside tmux for Ghostty
set -as terminal-features ",xterm-256color:stylus"

# Fix escape time delay inside Neovim
set -sg escape-time 10

set -g display-time 4000

set -g focus-events on

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

set -g status-position bottom
set -g status-style fg="#202020",bg="#ebf5ff"
set -g message-style fg="#202020",bg="#ffdf5d"
set -g pane-border-style fg="#d7e2ea"
set -g pane-active-border-style fg="#558855"
set -g window-status-style fg="#505050",bg="#ebf5ff"
set -g window-status-current-style fg="#000000",bg="#eaffea",bold
set -g status-left "#[bold] #S "
set -g status-right " %Y-%m-%d %H:%M "


# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

bind R source-file '~/.tmux.conf'
