set -g mouse on
set-option -g prefix C-a

bind C-a send-prefix
bind a last-window

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed

set -g set-titles on          # set terminal title

set -g history-limit 50000    # boost history

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g display-time 4000

set -g focus-events on

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

set -g status-style fg=white 


# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

bind R source-file '~/.tmux.conf'

